#ifndef OPCODE_H
#define OPCODE_H

#define OPCODE_OPEN_PAGE_HOME 1
#define OPCODE_PLUS 2
#define OPCODE_MINUS 3
#define OPCODE_OPEN_MENU 4
#define OPCODE_HR_ON 5
#define OPCODE_HR_OFF 6
#define OPCODE_SWITCH_MODE 7
#define OPCODE_REFRESH_TEMP_VALUES_ON_SCREEN 8
#define OPCODE_OPEN_PAGE_TEMPERATURE_SETTINGS 9

#endif