#ifndef OPCODE_H
#define OPCODE_H

/**
 * Contextual
 */
#define OPCODE_CONTEXTUAL_MINUS 1
#define OPCODE_CONTEXTUAL_PLUS 2
#define OPCODE_CONTEXTUAL_EDIT 3
#define OPCODE_CONTEXTUAL_NEXT 4
#define OPCODE_CONTEXTUAL_CANCEL 5
#define OPCODE_CONTEXTUAL_SAVE 6

#define OPCODE_OPEN_PAGE_HOME 101
#define OPCODE_OPEN_PAGE_SETTINGS 102
#define OPCODE_HR_ON 103
#define OPCODE_HR_OFF 104
#define OPCODE_SWITCH_MODE 105
#define OPCODE_HR_MODE_AUTO 106
#define OPCODE_HR_MODE_MANUAL 107
#define OPCODE_REFRESH_TEMP_VALUES_ON_SCREEN 108

#endif